[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM7
monitor_port = COM7

src_dir = src
include_dir = include

lib_deps = 
    https://github.com/BoschSensortec/Bosch-BME68x-Library.git
    https://github.com/BoschSensortec/Bosch-BSEC2-Library.git#v1.5.2400
    bblanchon/ArduinoJson @ ^6.21.5
    knolleary/PubSubClient @ ^2.8
    adafruit/Adafruit BME680 Library @ ^2.0.0
    adafruit/Adafruit Unified Sensor @ ^1.1.6

build_flags =
    -DBME68X_USE_SPI 
    -I.pio/libdeps/esp32dev/bsec2/src
    -I.pio/libdeps/esp32dev/bsec2/src/inc
    -I.pio/libdeps/esp32dev/bsec2/src/config
    -I.pio/libdeps/esp32dev/BME68x\ Sensor\ library/src
    -I../iot
    -I../iot/presence_model
    -I../iot/type_model
    -I../iot/red_region_model
    -I../iot/white_region_model
    
#.\.venv\Scripts\Activate.ps1
#Set-Alias -Name pio -Value "D:\Valencia\MQTT\.venv\Scripts\pio.exe"
#pio run